application:
  version: '@project.version@'
  locale-name: eng_US
spring:
  datasource:
    url: jdbc:h2:mem:testdb3
    initialization-mode: always
    schema: schema.sql
    data: data.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    enabled: false
