application:
  version: '@project.version@'
spring:
  datasource:
    url: jdbc:h2:mem:testdb3
    initialization-mode: always
    schema: classpath:/schema.sql
    data: classpath:/data.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8085
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: metrics, health, logfile
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
      show-details: always
    logfile:
      enabled: true
logging:
  file:
    name: app.log

