application:
  version: '@project.version@'
  locale-name: eng_US
spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
jdbc:
  h2:
    mem: testdb
